### ISSUE TITLE
document APIs

### ISSUE THREAD

**Issue by anushkmittal** [samcrane8/FlyRight#1]
we should have a README.md for the specs of these REST APIs

**Comment by samcrane8** [comment]
Great point, I am going to start working on that.

**Comment by samcrane8** [comment]
https://github.com/samcrane8/FlyRight/tree/master/docs

Okay, I had to fork and fix their repo, but Postdown has a way to generate readmes from postman that will be useful. We now have documentation, though there could be more descriptions.
