### ISSUE TITLE
Calendar View

### ISSUE THREAD

**Issue by Tonewall** [samcrane8/FlyRight#17]
Jeff would want a calendar feature kind of like the one from Google Calendar so he could look at the calendar to see where and what time there are registered flights for a certain day.

**Comment by samcrane8** [comment]
Great! I think a good place to put that would be as an alternative view for the flights page. This is also something you can entirely accomplish without modifying the back-end which makes it accessible.

What help do you need? I can give you some guidance on how to start this project.

**Comment by Tonewall** [comment]
I can start on this late this week and I'll let you know if I need help along the way!
