### ISSUE TITLE
register user not working?

### ISSUE THREAD

**Issue by anushkmittal** [samcrane8/FlyRight#2]
<img width="961" alt="Screen Shot 2019-05-06 at 9 16 19 PM" src="https://user-images.githubusercontent.com/13961658/57265173-4ccb7500-7044-11e9-916c-583064ff92a3.png">

(header has the application/json content-type)

**Comment by samcrane8** [comment]
ahhh sorry about this, this again growing pains of the repository going from personal project to open-sourced. The best practice way to create a user is through `/pilot/register/` rather than `/user/register/`. I am going to deprecate that part of the API and remove the /user/register/ endpoint code since it's unnecessary.

Let me know if you get it working then.

**Comment by anushkmittal** [comment]
`pilot/register` is actually throwing 404 not found

```
<h1>Not Found</h1>
<p>The requested URL /plitot/register was not found on this server.</p>
```

**Comment by anushkmittal** [comment]
<img width="979" alt="Screen Shot 2019-05-10 at 6 58 02 PM" src="https://user-images.githubusercontent.com/13961658/57560681-8e666380-7355-11e9-8008-27f20a38eda0.png">

**Comment by samcrane8** [comment]
You put down /plitot/register, but it should be /pilot/register/.

**Comment by anushkmittal** [comment]
ahh my bad. but now it's bback to

{
    "detail": "Method \"GET\" not allowed."
}

**Comment by samcrane8** [comment]
You need to put the last backslash on it. I am not sure why django is so particular about that, also the error is not really descriptive. Let me know if that works.

**Comment by anushkmittal** [comment]
yes, it works!

btw, need to update documentation. these are the required fields:

```
{ 
	"username": "anushk_test",
	"password": "anushk_test",
	"email": "anushk_test@gmail.com",
	"mobile_phone_number": "4247718471",
	"remote_pilot_certificate_number": "456",
	"first_name": "anushk_test",
	"last_name": ""
}
```
