### ISSUE TITLE
Setup Drone + Department on Dev Build

### ISSUE THREAD

**Issue by samcrane8** [samcrane8/FlyRight#22]
It's great that an admin user is automatically generated, but several other things should be autogenerated as well:

- autogenerate a department.
- autogenerate a drone that is owned by the admin user
- make the admin user an airboss of the department

**Comment by Tonewall** [comment]
Now that I thought of it, for autogenerating a department, should I just create a giant department that covers pretty much the whole world? Since we don't know where people will be developing from, an autogenerated department could be generated at a far place from the map and they'll have to scroll to that location every time.

**Comment by samcrane8** [comment]
That's actually the reason why I didn't set it up in the first place: because like you said, we don't know where people will be when they use this.

I'd say do a department at roughly the same size as GTPD, or even honestly just copy GTPD. If we start getting users like that then we can adapt and try to fix it, but that's a problem that we can solve when it happens. Plus I don't want to give people the wrong idea of how large departments generally are.

**Comment by Tonewall** [comment]
Alright yeah, that makes sense.

**Comment by samcrane8** [comment]
Cool. Also as a reminder, the file you will want to edit is called business-logic-server/create_superuser.py

Also, maybe change the name of the file to something more accurate, like setup_user_and_department.py? The only other file you will have to change is business-logic-server/entrypoint.sh since that's the file that calls this script.

**Comment by Tonewall** [comment]
Noted, I think we'll start working on the other projects I mentioned tomorrow so I'll try to see how far I can get before it gets interrupted

**Comment by samcrane8** [comment]
👍
