### ISSUE TITLE
generating client_secret and client_id

### ISSUE THREAD

**Issue by anushkmittal** [samcrane8/FlyRight#3]
so API gives back bearer auth_token

but we need to have a way to generate client_secret and  client_id as well as refrenced in login API

https://github.com/samcrane8/FlyRight/blob/4aeeda6dcadfde3e72346ae593686c74367e4ba2/postman_collection.json#L714

**Comment by samcrane8** [comment]
Good point.

We are using the OAuth2 toolkit for Django. [Here](https://django-oauth-toolkit.readthedocs.io/en/latest/rest-framework/getting_started.html) is the documentation. Here is the section on registering applications:

`
Step 3: Register an application

To obtain a valid access_token first we must register an application. DOT has a set of customizable views you can use to CRUD application instances, just point your browser at:

http://localhost:8000/o/applications/

Click on the link to create a new application and fill the form with the following data:

    Name: just a name of your choice
    Client Type: confidential
    Authorization Grant Type: Resource owner password-based

Save your app!
`

I am going to go ahead and put this into the docs readme section of the repository. Does this solve the issue?

**Comment by anushkmittal** [comment]
alright. this looks good.

**Comment by samcrane8** [comment]
Ahh actually I think this still might be an issue, I'm not sure how to create new applications without being an admin in the django server.. for the time being I can just give you client_id and client_secret to work with.

**Comment by anushkmittal** [comment]
alright can you send me that. thnx

**Comment by samcrane8** [comment]
I emailed them to you.
