### ISSUE TITLE
Issue with Changing Clearance Status

### ISSUE THREAD

**Issue by samcrane8** [samcrane8/FlyRight#7]
<img width="709" alt="Screen Shot 2019-05-20 at 3 00 10 PM" src="https://user-images.githubusercontent.com/3209813/58045287-02e89180-7b10-11e9-8420-9a1d73cf837a.png">

When we want to change the clearance the old clearance write-up is deleted. Can we make it so we can just edit it?

**Comment by Tonewall** [comment]
Hey Sam, I didn't have permission to publish my branch but...

In FlightDetailsInfo.vue (line 104) I think if you change:
        :placeholder="flight.clearance.message"
to:
        :value="flight.clearance.message"
it should fix the issue

**Comment by samcrane8** [comment]
Okay great! sorry for the delay, I've been abroad. Can you fork the repository and then do a pull request?

**Comment by Tonewall** [comment]
Just did 👍

**Comment by Tonewall** [comment]
#8
